# Generated by Django 4.2.7 on 2026-01-20 13:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=200, verbose_name='Title (English)')),
                ('title_ar', models.CharField(max_length=200, verbose_name='Title (Arabic)')),
                ('description_en', models.TextField(verbose_name='Description (English)')),
                ('description_ar', models.TextField(verbose_name='Description (Arabic)')),
                ('location_en', models.CharField(max_length=200, verbose_name='Location (English)')),
                ('location_ar', models.CharField(max_length=200, verbose_name='Location (Arabic)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('property_type', models.CharField(choices=[('Apartment', 'Apartment'), ('Villa', 'Villa'), ('Land', 'Land'), ('Office', 'Office')], max_length=20)),
                ('sale_type', models.CharField(choices=[('Sale', 'For Sale'), ('Rent', 'For Rent')], max_length=10)),
                ('phone', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/%Y/%m/%d/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
            options={
                'verbose_name': 'Property Image',
                'verbose_name_plural': 'Property Images',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
